import { MentiPresentation, MentiSlide } from "./menti";

export const MOCK_SLIDES: MentiSlide[] = [
  {
    id: "slide-1",
    presentationId: "demo-pres-1",
    type: "BAR_GRAPH",
    question: "Which web framework do you prefer for high-scale apps?",
    description: "Single choice bar chart",
    visualizationType: "BAR",
    position: 0,
    totalResponses: 42,
    options: [
      { id: "opt-1", label: "Next.js (App Router)", voteCount: 24, color: "#2d5cf6" },
      { id: "opt-2", label: "Remix / React Router v7", voteCount: 10, color: "#e11d48" },
      { id: "opt-3", label: "Vite + SPA", voteCount: 8, color: "#10b981" },
    ],
    responseSettings: {
      multipleSelection: false,
      showResultsAsPercentage: true,
      isVotingLocked: false,
    },
    designSettings: {
      backgroundColor: "#ffffff",
      textColor: "#1a1d29",
      accentColor: "#2d5cf6",
      showLogo: true,
    },
  },
  {
    id: "slide-2",
    presentationId: "demo-pres-1",
    type: "BAR_GRAPH",
    question: "Which features are most critical for your engineering stack?",
    description: "Multiple choices permitted (multi-checkbox)",
    visualizationType: "BAR",
    position: 1,
    totalResponses: 38,
    options: [
      { id: "opt-4", label: "End-to-end Type Safety", voteCount: 35, color: "#2d5cf6" },
      { id: "opt-5", label: "Real-time WebSockets / SSE", voteCount: 28, color: "#8b5cf6" },
      { id: "opt-6", label: "Instant Edge Caching", voteCount: 20, color: "#f59e0b" },
      { id: "opt-7", label: "Micro-frontends", voteCount: 6, color: "#64748b" },
    ],
    responseSettings: {
      multipleSelection: true,
      maxSelections: 3,
      showResultsAsPercentage: false,
      isVotingLocked: false,
    },
    designSettings: {
      backgroundColor: "#ffffff",
      textColor: "#1a1d29",
      accentColor: "#2d5cf6",
      showLogo: true,
    },
  },
  {
    id: "slide-3",
    presentationId: "demo-pres-1",
    type: "WORD_CLOUD",
    question: "Describe your dream dev workflow in 1-2 words",
    description: "Text inputs dynamically scaling in a live word cloud",
    position: 2,
    totalResponses: 54,
    options: [
      { id: "wc-1", label: "Fast", voteCount: 18 },
      { id: "wc-2", label: "Seamless", voteCount: 14 },
      { id: "wc-3", label: "Automated", voteCount: 11 },
      { id: "wc-4", label: "Delightful", voteCount: 9 },
      { id: "wc-5", label: "Reliable", voteCount: 8 },
      { id: "wc-6", label: "Typesafe", voteCount: 7 },
      { id: "wc-7", label: "Intuitive", voteCount: 5 },
      { id: "wc-8", label: "Modern", voteCount: 4 },
    ],
    responseSettings: {
      maxEntriesPerParticipant: 3,
      isVotingLocked: false,
    },
    designSettings: {
      backgroundColor: "#ffffff",
      textColor: "#1a1d29",
      accentColor: "#2d5cf6",
      showLogo: true,
    },
  },
  {
    id: "slide-4",
    presentationId: "demo-pres-1",
    type: "WORD_CLOUD",
    question: "What is your biggest engineering bottleneck right now?",
    description: "Single free-form response",
    position: 3,
    totalResponses: 19,
    options: [
      { id: "ans-1", label: "CI/CD build times", voteCount: 12 },
      { id: "ans-2", label: "Flaky test suites", voteCount: 8 },
      { id: "ans-3", label: "Outdated documentation", voteCount: 5 },
    ],
    responseSettings: {
      maxEntriesPerParticipant: 1,
      isVotingLocked: false,
    },
    designSettings: {
      backgroundColor: "#ffffff",
      textColor: "#1a1d29",
      accentColor: "#2d5cf6",
      showLogo: true,
    },
  },
  {
    id: "slide-5",
    presentationId: "demo-pres-1",
    type: "SCALES",
    question: "How confident are you in launching to production this week?",
    description: "Rate on a scale from 1 (Not confident) to 5 (Extremely confident)",
    position: 4,
    totalResponses: 30,
    options: [
      { id: "rate-1", label: "1", voteCount: 2 },
      { id: "rate-2", label: "2", voteCount: 3 },
      { id: "rate-3", label: "3", voteCount: 7 },
      { id: "rate-4", label: "4", voteCount: 12 },
      { id: "rate-5", label: "5", voteCount: 6 },
    ],
    responseSettings: {
      minRating: 1,
      maxRating: 5,
      ratingLowLabel: "Not confident",
      ratingHighLabel: "Extremely confident",
      isVotingLocked: false,
    },
    designSettings: {
      backgroundColor: "#ffffff",
      textColor: "#1a1d29",
      accentColor: "#2d5cf6",
      showLogo: true,
    },
  },
];

export const MOCK_PRESENTATION: MentiPresentation = {
  id: "demo-pres-1",
  title: "Engineering All-Hands & Strategy Sync",
  slug: "engineering-all-hands-2026",
  joinCode: "8239 2324",
  isLive: true,
  activeSlideId: "slide-1",
  ownerId: "user-1",
  participantCount: 42,
  slides: MOCK_SLIDES,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};
