FROM node:22-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

COPY apps/web/public /app/apps/web/public
COPY apps/web/.next/standalone /app
COPY apps/web/.next/static /app/apps/web/.next/static

EXPOSE 3000

CMD node apps/web/server.js
