FROM node:22-alpine AS runner
WORKDIR /app

COPY dist/api /app/api
COPY dist/db /app/db

EXPOSE 8000
ENV NODE_ENV=production
ENV PORT=8000

CMD cd /app/db && node migrate.mjs && cd /app/api && node dist/index.js
